# Generated by Django 3.2.9 on 2021-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dic',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ic',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
