# Generated by Django 3.2.9 on 2021-11-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211108_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
