# Generated by Django 3.2.9 on 2021-11-08 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211108_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(blank=True, max_length=8)),
                ('supplier', models.CharField(blank=True, max_length=128, null=True)),
                ('subscriber', models.CharField(blank=True, max_length=128, null=True)),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('account_number', models.CharField(blank=True, max_length=128)),
                ('variable_symbol', models.CharField(blank=True, max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.FloatField(blank=True, default=0)),
                ('dph', models.FloatField(blank=True, default=21)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
