# Generated by Django 3.2.9 on 2021-11-13 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('subscriber_name', models.CharField(blank=True, max_length=128, null=True)),
                ('subscriber_ic', models.CharField(blank=True, max_length=128, null=True)),
                ('subscriber_dic', models.CharField(blank=True, max_length=128, null=True)),
                ('subscriber_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('subscriber_address', models.CharField(blank=True, max_length=128, null=True)),
                ('subscriber_city', models.CharField(blank=True, max_length=64, null=True)),
                ('subscriber_country', models.CharField(blank=True, max_length=128, null=True)),
                ('subscriber_postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('date_exposure', models.DateField(default=datetime.datetime(2021, 11, 13, 21, 25, 38, 557213))),
                ('date_maturity', models.DateField(default=datetime.datetime(2021, 12, 13, 21, 25, 38, 557213))),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('account_number', models.CharField(blank=True, max_length=128)),
                ('variable_symbol', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(default='Put some text here for subscriber...', max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.FloatField(blank=True, default=0)),
                ('amouth', models.IntegerField(blank=True, default=1)),
                ('dph', models.FloatField(blank=True, default=21)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.invoice')),
            ],
        ),
    ]
