# Generated by Django 3.2.9 on 2021-11-14 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211114_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 14, 11, 58, 12, 66648)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 11, 58, 12, 66648)),
        ),
    ]
