# Generated by Django 3.2.9 on 2021-11-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_about_me'),
        ('orders', '0002_auto_20211108_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='order_id',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='order_id',
            new_name='invoice_id',
        ),
    ]
