# Generated by Django 3.2.9 on 2021-11-14 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211114_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 14, 14, 55, 3, 671667)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 14, 55, 3, 671667)),
        ),
        migrations.AlterField(
            model_name='item',
            name='amouth',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dph',
            field=models.FloatField(blank=True, default=21, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
