# Generated by Django 3.2.9 on 2021-11-10 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211110_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='subscriber',
            new_name='subscriber_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_expiration',
            field=models.DateField(default=datetime.datetime(2021, 11, 10, 20, 33, 35, 278164)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 10, 20, 33, 35, 278164)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber_country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber_dic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber_email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber_ic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber_postal_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='text',
            field=models.TextField(default='Put some text here for subscriber...', max_length=256),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
