# Generated by Django 3.2.9 on 2021-11-15 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211114_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=128, null=True, unique=True)),
                ('ic', models.CharField(max_length=128, null=True)),
                ('dic', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('postal_code', models.CharField(max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_id']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_dic',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_ic',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscriber_postal_code',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 9, 19, 38, 746953)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 15, 9, 19, 38, 747454)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.client'),
        ),
    ]
