# Generated by Django 3.2.9 on 2021-11-10 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211110_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_expiration',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 10, 22, 10, 51, 406836)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 10, 22, 10, 51, 406836)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
