# Generated by Django 3.2.9 on 2021-11-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211115_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='client_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='city',
            new_name='client_city',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='country',
            new_name='client_country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='dic',
            new_name='client_dic',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='ic',
            new_name='client_ic',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='postal_code',
            new_name='client_postal_code',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 10, 21, 57, 390743)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 15, 10, 21, 57, 390743)),
        ),
    ]
