# Generated by Django 3.2.9 on 2021-11-10 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211110_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amouth',
            field=models.ImageField(blank=True, default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 10, 22, 39, 33, 578023)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 10, 22, 39, 33, 578023)),
        ),
    ]
