# Generated by Django 3.2.9 on 2021-11-10 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211110_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 10, 22, 41, 13, 703691)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 10, 22, 41, 13, 703691)),
        ),
        migrations.AlterField(
            model_name='item',
            name='amouth',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
