# Generated by Django 3.2.9 on 2021-11-17 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20211117_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_exposure',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 19, 55, 19, 734857)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_maturity',
            field=models.DateField(default=datetime.datetime(2021, 12, 17, 19, 55, 19, 734857)),
        ),
        migrations.AlterField(
            model_name='item',
            name='amouth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='dph',
            field=models.FloatField(default=21),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
